### ISSUE TITLE
Reverse logic to limit code in if statement

### ISSUE THREAD

**Issue by TheBrockEllis** [raywagner88/bankingSimulation#1]
https://github.com/raywagner88/bankingSimulation/blob/39277440cd5b7e81da132c43a82ba2021cffca8e/bankingSimulation.html#L72

If you reverse of logic of `if (this.current_bill > 0) {` you can remove one set of large curly brackets.

Right now, the entire content of the `payBill()` method will run is they have a current bill. The way you have it written here means all of the method content is inside one large set of if statement curly brackets starting on line 72 and ending on line 111.  If you check for `if(this.current_bull <= 0)` then you can quickly `return` out of the method if they don't have a bill, you can continue on with the content.

i.e.

```
if(this.current_bill <= 0) { 
  this.messageToUser('No bill to pay');
  return; 
}

this.messageToUser(`Your bill is $${this.current_bill}.`);
...
```

**Comment by raywagner88** [comment]
Updated logic as requested.
